Deal with uninitialized repo for TDD

diff --git a/git/git-tdd b/git/git-tdd
--- a/git/git-tdd
+++ b/git/git-tdd
@@ -5,7 +5,7 @@ set -e
 set -o pipefail
 
 progname=${0##*/}
-trap 'r=$? ; (( 0 == $r )) || echo "$progname: Failed" ; exit $r' EXIT
+trap 'r=$? ; (( 0 == $r )) || echo "$progname: Failed." ; exit $r' EXIT
 
 function usage {
     echo "Usage: $progname <init|show|test|accept>"
@@ -39,6 +39,7 @@ function config {
 }
 
 function show {
+    _require-init
     git log -1 --notes=tdd "$@"
 }
 
@@ -61,6 +62,18 @@ Accept command (git config --local tdd.acceptCommand): $(config acceptCommand)
 EOM
 }
 
+function _has-init {
+    [[ -n "$(test-number)" ]]
+}
+
+function _require-init {
+    if ! _has-init
+    then
+        echo "$progname: TDD not initialized (try 'git tdd init')" >&2
+        exit 2
+    fi
+}
+
 function init {
     local quiet=false
     while (( 0 < $# ))
@@ -72,7 +85,7 @@ function init {
         esac
         shift
     done
-    if [[ -n "$(test-number)" ]]
+    if _has-init
     then
         echo "$progname: TDD already initialized" >&2
         exit 2
@@ -121,6 +134,7 @@ function test {
             * ) usage >&2 ; exit 2 ;;
         esac
     done
+    _require-init
     _are-there-changes || return 0
     _has-upstream \
         && _should-pull-before-test \
@@ -141,6 +155,7 @@ function accept {
             * ) usage >&2 ; exit 2 ;;
         esac
     done
+    _require-init
     $(config acceptCommand)
     local -r next=$(( $(test-number) + 1 ))
     if [[ -n "$message" ]]
