Progress; incomplete

diff --git a/git-merge-svn/lib/testing-functions b/git-merge-svn/lib/testing-functions
--- a/git-merge-svn/lib/testing-functions
+++ b/git-merge-svn/lib/testing-functions
@@ -7,19 +7,18 @@ set -o pipefail
 let pass=0 fail=0 error=0 && true
 
 function pass {
-    local message="$1"
-    echo "$0: $test_name: $message"
+    echo "$0: PASS: $test_name"
     let ++pass
 }
 
 function fail {
     local message="$1"
-    echo "$0: $test_name: $message" >&2
+    echo "$0: FAIL: $test_name: $message" >&2
     let ++fail
 }
 
 function error {
     local message="$1"
-    echo "$0: $test_name: $message: $scenario_text" >&2
+    echo "$0: ERROR: $test_name: $message: $scenario_text" >&2
     let ++error
 }
